**MATRIX INVERSE**

In [1]:
import numpy as np
from numpy import linalg

a = np.array([[1,3],[3,2]])
print(a)

[[1 3]
 [3 2]]


In [2]:
linalg.pinv(a)

array([[-0.28571429,  0.42857143],
       [ 0.42857143, -0.14285714]])



**MATRIX MULTIPLICATION**

In [3]:
b = np.array([[3,1],[4,6]])
print(b)

[[3 1]
 [4 6]]


In [4]:
a*b

array([[ 3,  3],
       [12, 12]])